# Import packages

In [1]:
import os
import src
import src.extract.from_db
import src.transform.by_aggregation
import src.transform.by_adding_attribute
import pandas as pd
from src import features
from src import database
import yfinance as yf
from config import ROOT_DIR

In [2]:
db_file = "/home/hao/repositories/dashboard-listing-securities/app/backend/database.db"
attribute = "isinId"  # For example, if you want to process the 'accountId' attribute
dict_attribute = src.extract.from_db.by_attribute(db_file, attribute)
df_attribute = pd.DataFrame(dict_attribute)
df_attribute

Successfully connected to /home/hao/repositories/dashboard-listing-securities/app/backend/database.db

,date,isin,name,type,quantity,unitPrice,total
0,2023-10-16,LU0131510165,Independance et Expansion France Small A,OPVCM,2.000000,652.06,1304.120000
1,2023-10-16,LU1832174962,Independance et Expansion Europe Small A,OPVCM,15.000000,130.30,1954.500000
2,2023-10-24,LU1832174962,Independance et Expansion Europe Small A,OPVCM,1.000000,126.95,126.950000
3,2023-10-24,LU0131510165,Independance et Expansion France Small A,OPVCM,1.000000,626.81,626.810000
4,2023-11-13,LU1832174962,Independance et Expansion Europe Small A,OPVCM,1.000000,131.87,131.870000
...,...,...,...,...,...,...,...
61,2024-06-03,US0846707026,Berkshire Hathaway Inc.,STOCK,0.793965,377.85,299.999675
62,2024-06-10,US0846707026,Berkshire Hathaway Inc.,STOCK,0.780335,384.45,299.999791
63,2024-06-10,US5705351048,Markel Group Inc.,STOCK,0.101557,1477.00,149.999689
64,2024-06-17,US5705351048,Markel Group Inc.,STOCK,0.104022,1442.00,149.999724
65,2024-06-17,US0846707026,Berkshire Hathaway Inc.,STOCK,0.792602,378.50,299.999857

In [3]:
dict_groupby_attribute = src.transform.by_aggregation.sum_by_attribute("isin", df_attribute)
dict_groupby_attribute

{'isin': ['LU0131510165',
  'LU1832174962',
  'LU1832175001',
  'LU1964632324',
  'US0846707026',
  'US5705351048'],
 'quantity': [9.0, 40.0, 9.0, 1.0, 21.154106, 2.021525]}

In [4]:
isin_list = src.transform.by_adding_attribute.last_price("isin", dict_groupby_attribute)
isin_list

{'isin': ['LU0131510165',
  'LU1832174962',
  'LU1832175001',
  'LU1964632324',
  'US0846707026',
  'US5705351048'],
 'quantity': [9.0, 40.0, 9.0, 1.0, 21.154106, 2.021525],
 'previousClosePrice': [767.91, 154.75, 159.19, 863.15, 410.26, 1569.59],
 'totalClosePrice': [6911.19,
  6190.0,
  1432.71,
  863.15,
  8678.683527559999,
  3172.96542475]}

In [15]:
# Example usage
db_file = "/home/hao/repositories/dashboard-listing-securities/app/backend/database.db"
result = from_db.all_attributes(db_file)
pd.DataFrame(result)

Successfully connected to /home/hao/repositories/dashboard-listing-securities/app/backend/database.db

,date,isin,isin_name,isin_type,broker_name,broker_country,account_number,account_name,order_type,quantity,unitPrice,total
0,2023-10-16,LU0131510165,Independance et Expansion France Small A,OPVCM,BourseDirect,FRANCE,508TI00083440250EUR,PEA,SELL,2.000000,652.06,1304.120000
1,2023-10-16,LU1832174962,Independance et Expansion Europe Small A,OPVCM,BourseDirect,FRANCE,508TI00084026141EUR,PEA-PME,SELL,15.000000,130.30,1954.500000
2,2023-10-24,LU1832174962,Independance et Expansion Europe Small A,OPVCM,BourseDirect,FRANCE,508TI00084026141EUR,PEA-PME,SELL,1.000000,126.95,126.950000
3,2023-10-24,LU0131510165,Independance et Expansion France Small A,OPVCM,BourseDirect,FRANCE,508TI00083440250EUR,PEA,SELL,1.000000,626.81,626.810000
4,2023-11-13,LU1832174962,Independance et Expansion Europe Small A,OPVCM,BourseDirect,FRANCE,508TI00084026141EUR,PEA-PME,SELL,1.000000,131.87,131.870000
...,...,...,...,...,...,...,...,...,...,...,...,...
61,2024-06-03,US0846707026,Berkshire Hathaway Inc.,STOCK,TradeRepublic,GERMANY,0422720001,CTO,SELL,0.793965,377.85,299.999675
62,2024-06-10,US0846707026,Berkshire Hathaway Inc.,STOCK,TradeRepublic,GERMANY,0422720001,CTO,SELL,0.780335,384.45,299.999791
63,2024-06-10,US5705351048,Markel Group Inc.,STOCK,TradeRepublic,GERMANY,0422720001,CTO,SELL,0.101557,1477.00,149.999689
64,2024-06-17,US5705351048,Markel Group Inc.,STOCK,TradeRepublic,GERMANY,0422720001,CTO,SELL,0.104022,1442.00,149.999724
65,2024-06-17,US0846707026,Berkshire Hathaway Inc.,STOCK,TradeRepublic,GERMANY,0422720001,CTO,SELL,0.792602,378.50,299.999857

# Load dataset

In [16]:
# Build the full path to the CSV file
csv_file_path = os.path.join(ROOT_DIR, 'app', 'backend', 'transaction.csv')

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(csv_file_path)

In [5]:
df.head()

   id  isinId  brokerId  accountId        date  orderId  quantity  unitPrice
0   1       1         1          1  2023-10-16        1       2.0     652.06
1   2       3         1          2  2023-10-16        1      15.0     130.30
2   3       3         1          2  2023-10-24        1       1.0     126.95
3   4       1         1          1  2023-10-24        1       1.0     626.81
4   5       3         1          2  2023-11-13        1       1.0     131.87

# Add features

In [6]:
df_features = features.add_column_total(df)
df_features.head()

,id,isinId,brokerId,accountId,date,orderId,quantity,unitPrice,total
0,1,1,1,1,2023-10-16,1,2.0,652.06,1304.12
1,2,3,1,2,2023-10-16,1,15.0,130.30,1954.50
2,3,3,1,2,2023-10-24,1,1.0,126.95,126.95
3,4,1,1,1,2023-10-24,1,1.0,626.81,626.81
4,5,3,1,2,2023-11-13,1,1.0,131.87,131.87

In [9]:
ticker_symbol = 'MKL'  # Replace with the actual ticker symbol corresponding to the ISIN

# Fetching the stock data using yfinance
stock = yf.Ticker('FR0000121014')

# Get the current price
current_price = stock.info['previousClose']
current_price

727.0

In [10]:
import yfinance as yf

# Fetching the stock data using yfinance
stock = yf.Ticker('FR0000121014')

# Get historical market data
hist = stock.history(period='5d')

# Extract the close prices and dates
close_prices = hist['Close'].tolist()
dates = hist.index.tolist()

# Combine the dates and close prices into a list of tuples
recent_closes = list(zip(dates, close_prices))

# Print the results
for date, close in recent_closes:
    print(f"Date: {date}, Close Price: {close}")

Date: 2024-06-21 00:00:00+02:00, Close Price: 717.2999877929688
Date: 2024-06-24 00:00:00+02:00, Close Price: 726.5
Date: 2024-06-25 00:00:00+02:00, Close Price: 736.7999877929688
Date: 2024-06-26 00:00:00+02:00, Close Price: 727.0
Date: 2024-06-27 00:00:00+02:00, Close Price: 715.5

In [11]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-21 00:00:00+02:00,712.700012,719.500000,710.400024,717.299988,902570,0.0,0.0
2024-06-24 00:00:00+02:00,718.000000,730.200012,716.700012,726.500000,262912,0.0,0.0
2024-06-25 00:00:00+02:00,722.099976,737.799988,721.099976,736.799988,315702,0.0,0.0
2024-06-26 00:00:00+02:00,738.599976,741.799988,720.299988,727.000000,314903,0.0,0.0
2024-06-27 00:00:00+02:00,726.599976,735.599976,714.599976,715.500000,288905,0.0,0.0

# Database

In [8]:
# Create database from csv
database.create_from_csv(
    os.path.join(ROOT_DIR, 'app', 'backend', 'transaction.csv'),
    os.path.join(ROOT_DIR, 'app', 'backend', 'database.db')
)

In [9]:
# List all tables of the database
all_tables = database.list_tables(
    os.path.join(ROOT_DIR, 'app', 'backend', 'database.db')
)
print(all_tables)

['account', 'broker', 'order', 'isin', 'transaction']